name: CI - Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Install root deps
        run: npm ci || npm i --no-audit --no-fund

      - name: Install backend deps
        run: |
          cd backend
          npm ci || npm i --no-audit --no-fund

      # Frontend dependencies step removed per request

      - name: Run backend tests
        env:
          NODE_ENV: test
        run: |
          cd backend
          npx jest --runInBand

      # Frontend tests removed per request
